[package]
edition = "2021"
name = "datafusion-objectstore-s3"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = {version = "8.0.0", features = ["prettyprint"]}
# arrow = {git = "https://github.com/apache/arrow-rs", rev = "fb581f30572e1237223209a88b395fc26ffa9a18", features = ["prettyprint"]}
async-trait = "0.1.52"
aws-config = "0.5.2"
aws-sdk-s3 = "0.5.2"
aws-smithy-async = "0.35.2"
aws-smithy-types = "0.35.2"
aws-smithy-types-convert = {version = "0", features = ["convert-chrono"]}
aws-types = "0.5.2"
bytes = "1.1.0"
datafusion = {git = "https://github.com/apache/arrow-datafusion", rev = "7b8d72c5342610a40827f23df7d5604cf24133fd"}
futures = "0.3.19"
http = "0.2.6"
num_cpus = "1.13.1"
tokio = {version = "1.0", features = ["macros", "rt", "rt-multi-thread", "sync", "fs"]}
